version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    container_name: postgres
    volumes:
      - postgres_12:/var/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8086:443
    depends_on:
      - web

volumes:
  postgres_12:
  static_volume: